### ISSUE TITLE
`var result = await videoKitRecorder.CaptureScreenshot();` causes the app to crash after time

### ISSUE THREAD

**Issue by SimonDarksideJ** [videokit-ai/videokit#155] opened 2024-11-11 22:47 UTC
# Summary

no logs as this only seems to exhibit in player testing on device and Unity does not seem to want to express anything, but I have finally managed to replicate the issue in a sample project
It had me going for a while as the issue DOES NOT occur in a normal Unity project, justa scene and running on the device
However
Where it does fall down is when XR is used, AR Foundation and ARCore in this instance ( I haven't re-tested on iOS as yet)
As soon as I enabled XR , configured the scene and added the new camera to the RecordingManager, the app just crashes after a second or two.

The image is taken, it can be shared, but crash.
However, in both test cases, XR and non-XR, the image could NOT be saved to the device / library using SaveToCameraRoll(), nothing appears on the device

## Sample Project
https://1drv.ms/u/s!Aptbw6KVYaU2kNsbM34e3tg5SfxoHw?e=4fpkg0

## Tested on

- VIdeoKit - V0.0.22-alpha2
- Function - V0.0.30

**Comment by SimonDarksideJ** [comment] 2024-11-11 23:24
I see full V22 is now out, but unable to re-test due to #156

**Comment by SimonDarksideJ** [comment] 2024-11-12 00:15
Re-tested with the latest VideoKit, no change in the issue.

Validated using the sample project attached with the latest release versions and it still crashes

**Comment by olokobayusuf** [comment] 2024-11-25 02:34
@SimonDarksideJ tried reproducing this on iOS, Android, and macOS editor, but have been unable to. I took a deeper look at the logs you shared and only noticed these:
```
Info scudo Scudo ERROR: misaligned pointer when deallocating address 0x0074c1e5ca08
...
Error CRASH pid: 8308, tid: 8355, name: GC Finalizer  >>> com.UnityTechnologies.com.unity.template.urpblank <<<
...
Error CRASH       #00 pc 000000000005b730  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: edc1b601d9f8344c1eccd3d77a458f65)
Error CRASH       #01 pc 0000000000048f20  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::map(void*, unsigned long, char const*, unsigned long, scudo::MapPlatformData*)) (BuildId: edc1b601d9f8344c1eccd3d77a458f65)
Error CRASH       #02 pc 00000000000498a8  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportHardRSSLimit(unsigned long)) (BuildId: edc1b601d9f8344c1eccd3d77a458f65)
Error CRASH       #03 pc 0000000000049e54  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportDeallocTypeMismatch(scudo::AllocatorAction, void*, unsigned char, unsigned char)) (BuildId: edc1b601d9f8344c1eccd3d77a458f65)
Error CRASH       #04 pc 000000000004b824  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)+296) (BuildId: edc1b601d9f8344c1eccd3d77a458f65)
```
These indicate that:
1. There's a pointer corruption (misaligned pointer) in the allocator that Unity uses (scudo)
2. The crashing thread is not the Unity main thread (where you call `CaptureScreenshot`), but in Unity's garbage collector thread `GC Finalizer`
3. The call stack doesn't mention the Unity main thread or the VideoKit native library.

This is a Unity bug. I'm closing this issue out.

**Closed by olokobayusuf** 2024-11-25 02:34 UTC
Labels: bug, critical

**Comment by SimonDarksideJ** [comment] 2024-11-25 09:30
Have you then logged this issue with Unity with the base code, as unity does not accept issues logged from assets.

And can you keep this issue open until Unity resolves it as only the creator has visibity of it.
Thanks @olokobayusuf

**Comment by olokobayusuf** [comment] 2024-11-25 13:24
@SimonDarksideJ to clarify, this issue isn't caused by VideoKit at all. It's a bug in Unity's garbage collector for their .NET runtime. You will have to submit the issue to Unity, or try changing Unity versions.

**Comment by SimonDarksideJ** [comment] 2024-11-25 14:58
Can you provide some sample code from the asset that causes the issue then please @olokobayusuf , as Unity will not accept bug reports without replication and do not accept bug reports with assets, even if it is their fault.

I'm happy to raise and manage the issue with Unity, but I need a sample that causes the issue.

**Comment by olokobayusuf** [comment] 2024-11-25 15:01
@SimonDarksideJ I was not able to reproduce it, because it is a garbage collector bug. The garbage collector has no overlap whatsoever with VideoKit.

**Comment by SimonDarksideJ** [comment] 2024-11-25 15:11
I shall endeavour to get the sample app tested on other devices.
