### ISSUE TITLE
ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by RajParab** [videokit-ai/videokit#129] opened 2024-06-25 08:04 UTC
I am trying to record video using VideoKit in an empty project but when I click the start button I get this error 

I am not exactly sure why is it not able to get the width of the screen

this is my recorder component
![image](https://github.com/natmlx/videokit/assets/47249678/6d598185-72cc-4d47-a4fd-e2b38e3327e5)
I did try all the options in Resolution 

It would be nice if anyone can tell what am I missing here 

Thanks

Full Stack - 
ArgumentException: Value does not fall within the expected range.
VideoKit.Internal.VideoKit.Throw (VideoKit.Internal.VideoKit+Status status) (at ./Library/PackageCache/ai.natml.videokit@0.0.18/Runtime/Internal/VideoKit.cs:851)
VideoKit.MediaRecorder.get_width () (at ./Library/PackageCache/ai.natml.videokit@0.0.18/Runtime/MediaRecorder.cs:94)
VideoKit.Sources.CameraSource..ctor (VideoKit.MediaRecorder recorder, VideoKit.Clocks.IClock clock, UnityEngine.Camera[] cameras) (at ./Library/PackageCache/ai.natml.videokit@0.0.18/Runtime/Sources/CameraSource.cs:59)
VideoKit.VideoKitRecorder.CreateVideoInput () (at ./Library/PackageCache/ai.natml.videokit@0.0.18/Runtime/Components/VideoKitRecorder.cs:647)
VideoKit.VideoKitRecorder.StartRecording () (at ./Library/PackageCache/ai.natml.videokit@0.0.18/Runtime/Components/VideoKitRecorder.cs:478)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <51fded79cd284d4d911c5949aff4cb21>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <834804db60ae4eb981294088cf979056>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <834804db60ae4eb981294088cf979056>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <834804db60ae4eb981294088cf979056>:0)

**Comment by olokobayusuf** [comment] 2024-06-25 14:45
Hey @RajParab , can you share the `Editor.log`? To get the editor logs, open the `Console` tag and in the top-right, there is an expander menu (three dots). Click it and open the editor logs. Try reproducing this error then share the logs once the exception is raised. Thanks.

**Comment by olokobayusuf** [comment] 2024-06-25 14:46
Also, are you on the macOS or Windows editor?

**Comment by RajParab** [comment] 2024-06-26 05:42
I am windows user 
Will share the console exceptions in some time

**Comment by RajParab** [comment] 2024-06-27 05:21
Hello @olokobayusuf 
Here is the editor Log file that you asked for
[Editor-log.txt](https://github.com/user-attachments/files/16008355/Editor-log.txt)

**Comment by olokobayusuf** [comment] 2024-06-28 01:11
Fix coming in 0.0.19.

**Comment by olokobayusuf** [comment] 2024-06-28 01:45
Fixed in 0.0.19.

**Comment by RajParab** [comment] 2024-06-28 06:42
Would like to know what was the issue and fix

**Comment by RajParab** [comment] 2024-06-28 11:15
After updating the application now the entire Unity App seems to be crashing

**Comment by olokobayusuf** [comment] 2024-06-28 13:01
> After updating the application now the entire Unity App seems to be crashing

I've reopened the issue. If you face errors or a crash, always include logs. It's impossible to know what the cause is from only stating that a crash happens.

**Comment by RajParab** [comment] 2024-06-29 07:15
Yes I should have attached the log

I missed that as I was busy with some other tasks

Here are the files that are being sent with the bug report to Unity

[crash-report.zip](https://github.com/user-attachments/files/16039153/crash-report.zip)

**Comment by RajParab** [comment] 2024-07-04 04:52
@olokobayusuf  Any update on this issue??

**Comment by olokobayusuf** [comment] 2024-07-12 16:16
@RajParab not yet, should have some news on Monday.

**Comment by olokobayusuf** [comment] 2024-08-07 19:06
@RajParab can you try out VideoKit 0.0.21? We haven't been able to reproduce this issue.

**Closed by olokobayusuf** 2024-08-07 19:06 UTC
Labels: bug, critical, windows
